[package]
name = "epibox"
version = "0.1.0"
authors = ["cgmossa <cgmossa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#enum_variant_type = "0.2.0"
enum-iterator = "0.5.0"